### ISSUE TITLE
Why can't delete products?

### ISSUE THREAD

**Issue by santoslopes** [woocommerce/wc-api-python#43]
The code for deleting products seems to be very simple:
`
from woocommerce import API
wcapi = API(    
    url="https://pentaculo.programamos.pt",
    consumer_key="ck_",
    consumer_secret="cs_",
    version="wc/v3",
    timeout=30    
)
print(wcapi.delete("products/109?force=true").json())
`
But get error:
`
Traceback (most recent call last):
  File "C:\Users\ASUS PC\AppData\Local\Programs\Python\Python36\loja.py", line 19, in <module>
    print(wcapi.delete("products/109?force=true").json())
  File "C:\Users\ASUS PC\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\ASUS PC\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ASUS PC\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ASUS PC\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`
Any help about this?
the code
`
print(wcapi.get("products").json())
`
works fine but I can't update a product either
`
data = {
    "regular_price": "24.54"
}
print(wcapi.put("products/109", data).json())
`
If I access to https://pentaculo.programamos.pt/wp-json/wc/v3/products
got
`
{"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot list resources.","data":{"status":401}}
`

**Comment by claudiosanches** [comment]
Seems like WordPress is forcing validation of `?force=true`.
I could delete using:

```python
print(wcapi.delete("products/109", params={"force": True}).json())
```
